name: server-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install NPM packages
        run: npm install
        shell: bash
        working-directory: n6-beta-feedesto-be-beta-6

      - name: Build project
        run: npm run build
        shell: bash
        working-directory: n6-beta-feedesto-be-beta-6
